### ISSUE TITLE
Add support for clusters file

### ISSUE THREAD

**Issue by dmedlin-git** [whme/csshw#10]
Would it be possible to add support for using a clusters file much like csshX uses to avoid having to enter long strings of hosts? Not sure if this is the preferred method for a feature request. Please close if not the right place.

**Comment by whme** [comment]
Yes this is the preferred method for a feature request 👍 
For reference the relevant [cssh manual](https://linux.die.net/man/1/cssh) excerpts:
(I assume the csshx option behaves the same)

> --cluster-file,-c <file>
> Use supplied file as additional cluster file (see also " FILES ")
>
> ### Files
> _/etc/clusters_
>
> This file contains a list of tags to server names mappings. When any name is used on the command line it is checked to see if it is a tag. If it is a tag, then the tag is replaced with the list of servers. The formated is as follows:
> \<tag\> [user@]\<server\> [user@]\<server\> [...]
>
> i.e.
> ```
> # List of servers in live
> live admin1@server1 admin2@server2 server3 server4
> ```
> All comments (marked by a #) and blank lines are ignored. Tags may be nested, but be aware of recursive tags which are not checked for.
> Clusters may also be specified either directly (see "clusters" configuration options) or indirectly (see "extra_cluster_file" configuration option) in the users $HOME/.csshrc file.
>
> NOTE: there is a special cluster tag called "default" - any tags or hosts included within this tag will be automatically opened if no other tags are specified on the command line.

Some questions from my side:
* is some default clusters file to be considered at all times or only if the `--clusters` option is provided?
 i.e. if `--clusters` isn't present or if it is used as a flag, should then some default clusters file be used? While otherwise the specified file should be used?
 Or should the clusters file only be used if explicitly given? i.e. `--clusters <path to file>`
* should nested tags be support or can support for them be added later on?
* should the special cluster tag "default" also be supported?
 if so, and if a default clusters file is used at all times, should executing `csshw.exe` without any hosts open ssh connections to all hosts specified under the "default" tag? Currently it will display the `--help` output.

**Comment by dmedlin-git** [comment]
> Yes this is the preferred method for a feature request 👍 For reference the relevant [cssh manual](https://linux.die.net/man/1/cssh) excerpts: (I assume the csshx option behaves the same)
> 
> > --cluster-file,-c 
> > Use supplied file as additional cluster file (see also " FILES ")
> > ### Files
> > _/etc/clusters_
> > This file contains a list of tags to server names mappings. When any name is used on the command line it is checked to see if it is a tag. If it is a tag, then the tag is replaced with the list of servers. The formated is as follows:
> > <tag> [user@]<server> [user@]<server> [...]
> > i.e.
> > ```
> > # List of servers in live
> > live admin1@server1 admin2@server2 server3 server4
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > All comments (marked by a #) and blank lines are ignored. Tags may be nested, but be aware of recursive tags which are not checked for.
> > Clusters may also be specified either directly (see "clusters" configuration options) or indirectly (see "extra_cluster_file" configuration option) in the users $HOME/.csshrc file.
> > NOTE: there is a special cluster tag called "default" - any tags or hosts included within this tag will be automatically opened if no other tags are specified on the command line.
> 
> Some questions from my side:
> 
> * is some default clusters file to be considered at all times or only if the `--clusters` option is provided?
>   i.e. if `--clusters` isn't present or if it is used as a flag, should then some default clusters file be used? While otherwise the specified file should be used?
>   Or should the clusters file only be used if explicitly given? i.e. `--clusters <path to file>`
> * should nested tags be support or can support for them be added later on?
> * should the special cluster tag "default" also be supported?
>   if so, and if a default clusters file is used at all times, should executing `csshw.exe` without any hosts open ssh connections to all hosts specified under the "default" tag? Currently it will display the `--help` output.


1. In my case I didn't add anything additional (like a config file) to tell it where to where to look for the clusters file as it uses Cluster SSH behavior of looking in /etc/clusters. I imagine there would need to be a default location established and stated in the readme/help section since /etc/ isn't a standard windows path and then if it's specified when launched then it's just overriding the default path. 
2. I do use nested tags to launch multiple groups but it's not an everday thing
3. I think the default behavior is sufficient.

I can open a new issue if it's preferred, but it would also be helpful to have control mode added. I use that pretty frequently to retile windows if I close a few as well as the toggle option to enable/disable input to certain windows. Not sure how feasible it would be to add this for Windows. Perhaps having the input window mirror what csshX does (opening along the bottom of the screen) since it's not really used to view any text. This could allow better use of screen space for the active windows.

**Comment by dmedlin-git** [comment]
1. In my case I didn't add anything additional (like a config file) to tell it where to where to look for the clusters file as it uses Cluster SSH behavior of looking in /etc/clusters. I imagine there would need to be a default location established and stated in the readme/help section since /etc/ isn't a standard windows path and then if it's specified when launched then it's just overriding the default path. 
2. I do use nested tags to launch multiple groups but it's not an everday thing
3. I think the default behavior is sufficient.

I can open a new issue if it's preferred, but it would also be helpful to have control mode added. I use that pretty frequently to retile windows if I close a few as well as the toggle option to enable/disable input to certain windows. Not sure how feasible it would be to add this for Windows. Perhaps having the input window mirror what csshX does (opening along the bottom of the screen) since it's not really used to view any text. This could allow better use of screen space for the active windows.

**Comment by whme** [comment]
> I can open a new issue if it's preferred, but it would also be helpful to have control mode added. 

Yes, please open a new issue for that 👍
